let data = {
  labels: {
    en: {
      dashboard: "Dashboard",
      login: "Login",
      username: "Username",
      password: "Password",
      submit: "Submit",
      or: "OR",
      signup: "Signup",
      accountType: "Account Type",
      agency: "Agency",
      fullNames: "Full Names",
      agencyWebsite: "Agency Website",
      email: "Email",
      agencyEmail: "Agency Email",
      agencyPhone: "Agency Phone",
      repeatPassword: "Repeat Password",
      agencyCountry: "Agency Country",
      operator: "Operator",
      flightSupport: "Flight Support",
      permits: "Permits",
      violations: "Violations",
      termsAndFees: "Terms & Fees",
      notams: "NOTAMS",
      healtAndImmigration: "Health & Immigration",
      users: "Users",
      account: "Account",
      openInvoices: "Open Invoices",
      overdue: "Overdue",
      paid: "Paid",
      new: "New",
      reload: "Reload",
      aircraft: "Aircraft",
      names: "Names",
      country: "Country",
      caoIdentifier: "CAO Identifier",
      iataIdentifier: "IATA Identifier",
      nationalCarrier: "National Carrier",
      actions: "Actions",
      registration: "Registration",
      model: "Model",
      type: "Type",
      homeBase: "Home Base",
      serialNumber: "Serial Number",
      seats: "Seats",
      back: "Back",

      permitType: "Permit Type",
      clearanceType: "Clearance Type",
      flightType: "Flight Type",
      clearanceDuration: "Clearance Duration",
      information: "Information",
      other: "Other",
      reviewAndAuthorize: "Review & authorize your payment",
      invoice: "Invoice",
      processingFees: "Processing fees",
      totalBill: "Total bill",
      paymentMethod: "Payment Method",
      authorizePayment: "Authorize Payment",
      yourBalanceIs: "Your balance is",
      landingPermit: "Landing Permit",
      overflyPermit: "Overfly Permit",
      single: "Single",
      block: "Block",
      multipleDaily: "Multiple daily",
      oneMonth: "One Month",
      threeMonths: "Three Months",
      bankTransfer: "Bank Transfer",
      myWallet: "My Wallet",

      flightRoute: "",
    },
    fr: {
      dashboard: "Tableau de bord",
      login: "Connexion",
      username: "Utilisateur",
      password: "Mot de passe",
      submit: "Envoyer",
      or: "OU",
      signup: "S'incrire",
      accountType: "Type de compte",
      agency: "Agence",
      fullNames: "Noms complete",
      agencyWebsite: "Site internet de l'agence",
      email: "Email",
      agencyEmail: "Email de l'Agence",
      agencyPhone: "Phone de l'Agence",
      repeatPassword: "Répéter le mot de passe",
      agencyCountry: "Pays de l'Agence",
      operator: "Opérateur",
      flightSupport: "Assistance en vol",
      permits: "Permis",
      violations: "Infractions",
      termsAndFees: "Conditions et frais",
      notams: "NOTAMS",
      healtAndImmigration: "Santé & Immigration",
      users: "Utilisateurs",
      account: "Compte",
      openInvoices: "Non Facturés",
      overdue: "Retardés",
      paid: "Payés",
      new: "Nouveau",
      reload: "Recharger",
      aircraft: "Avion",
      names: "Noms",
      country: "Pays",
      caoIdentifier: "Identifiant CAO",
      iataIdentifier: "Identifier IATA",
      nationalCarrier: "Transporteur National",
      actions: "Actions",
      registration: "Numero d'enregistrement",
      model: "Modèle",
      type: "Type",
      homeBase: "Port d'attache",
      serialNumber: "Numéro de série",
      seats: "Places",
      back: "Retourner",

      permitType: "Type de permis",
      clearanceType: "Type d'autorisation",
      flightType: "Type de vol",
      clearanceDuration: "Durée de l'autorisation",
      information: "Information",
      other: "Autre",
      reviewAndAuthorize: "Vérifiez & autorisez votre paiement",
      invoice: "Facture",
      processingFees: "Frais de traitement",
      totalBill: "Facture totale",
      paymentMethod: "Methode de paiement",
      authorizePayment: "Autoriser le paiement",
      yourBalanceIs: "Votre solde est",
      landingPermit: "Permis d'atterrissage",
      overflyPermit: "Permis de survol",
      single: "Unique",
      block: "Groupe",
      multipleDaily: "Plusieurs par jour",
      oneMonth: "Un mois",
      threeMonths: "Trois Mois",
      bankTransfer: "Virement",
      myWallet: "Mon Portefeuille",
    },
  },
  placeholders: {
    en: {
      selectAccountType: "Select account Type",
      selectCountry: "Select Country",
      periodStart: "Period Start",
      periodEnd: "Period End",
      moreInfo: "More information here...",

      flightNumber: "",
      departureAirport: "",
      depDate: "",
      depTime: "",
      arrivalAirport: "",
    },
    fr: {
      selectAccountType: "Type de compte",
      selectCountry: "Pays",
      periodStart: "Début de période",
      periodEnd: "Fin de période",
      moreInfo: "Plus d'informations ici...",
    },
  },
  messages: {
    en: {
      checkInputs: "Check your inputs !",
      noDataFound: "No data found !",
      checkDataService: "Check if the data service is up, and try again !",
    },
    fr: {
      checkInputs: "Vérifiez vos entrées ",
      noDataFound: "Aucune donnée disponible",
      checkDataService:
        "Vérifiez si le service de données est opérationnel et réessayez !",
    },
  },
};

module.exports = data;
